class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome_title': 'Track. Manage. Cancel.\nAll your subscriptions.',
      'welcome_subtitle': 'SubLens scans your Gmail to find subscriptions and helps you take control.',
      'get_started': 'Get Started',
      'connect_title': 'Connect your Gmail',
      'connect_desc': 'We\'ll securely access your emails to detect subscriptions. We never read or share your emails.',
      'connect_badge': 'We never read or share your emails',
      'continue_google': 'Continue with Google',
      'disconnect_anytime': 'You can disconnect anytime.',
      'scanning_title': 'Scanning your Gmail',
      'scanning_desc': 'Please wait while we analyze your emails for subscriptions.',
      'in_progress': 'In Progress',
      'stop_scan': 'Stop Scan',
      'emails_scanned': 'Emails scanned',
      'subs_found': 'Subscriptions found',
      'time_elapsed': 'Time elapsed',
      'hello': 'Hello, {name} 👋',
      'overview': 'Here\'s your subscription overview',
      'active_subs': 'Active Subscriptions',
      'monthly_spend': 'Monthly Spend',
      'recent_subs': 'Recent Subscriptions',
      'view_all': 'View all',
      'start_new_scan': 'Start New Scan',
      'your_subs': 'Your Subscriptions',
      'all': 'All',
      'active': 'Active',
      'canceled': 'Canceled',
      'billing_cycle': 'Billing Cycle',
      'next_charge': 'Next Charge',
      'last_charge': 'Last Charge',
      'detected_in': 'Detected In',
      'confidence': 'Confidence Score',
      'recent_emails': 'Recent Emails',
      'cancel_guide': 'Cancel Guide',
      'mark_canceled': 'Mark as Canceled',
      'how_to_cancel': 'How to cancel',
      'open_account': 'Open Account',
      'step_1_title': 'Go to Account',
      'step_1_desc': 'Visit the account settings page and sign in.',
      'step_2_title': 'Go to Billing',
      'step_2_desc': 'Navigate to profile > Billing or Subscription details.',
      'step_3_title': 'Cancel Membership',
      'step_3_desc': 'Click on \'Cancel Membership\' and confirm.',
      'step_4_title': 'Confirmation',
      'step_4_desc': 'You\'ll receive a confirmation email shortly.',
      'scan_history': 'Scan History',
      'insights': 'Insights',
      'monthly_spend_trend': 'Monthly Spend Trend',
      'top_categories': 'Top Categories',
      'total_saved': 'Total Saved',
      'this_month': 'This month',
      'settings': 'Settings',
      'account': 'Account',
      'preferences': 'Preferences',
      'scan_freq': 'Scan Frequency',
      'sync_range': 'Email Sync Range',
      'currency': 'Currency',
      'support': 'Support',
      'help_center': 'Help Center',
      'contact_us': 'Contact Us',
      'privacy': 'Privacy Policy',
      'terms': 'Terms of Service',
      'log_out': 'Log Out',
      'language': 'Language / 语言',
      
      // Bottom Navigation
      'nav_home': 'Home',
      'nav_subs': 'Subscriptions',
      'nav_scan': 'Scan',
      'nav_insights': 'Insights',
      'nav_settings': 'Settings',

      // Cycles & Statuses
      'status_active': 'Active',
      'status_canceled': 'Canceled',
      'cycle_monthly': 'Monthly',
      'cycle_yearly': 'Yearly',
      'cycle_one_time': 'One-time',
      'cycle_unknown': 'Unknown',
      'status_completed': 'Completed',

      // Home stats subtext
      'home_active_subtext': '+2 this month',
      'home_spend_subtext': '+\$12.30 this month',

      // Dynamic units
      'unit_month': '/ month',
      'unit_year': '/ year',
      'unit_emails_scanned': 'emails scanned',
      'unit_subs_found': 'subscriptions found',
      'no_subs_found': 'No subscriptions found.',

      // Categories
      'cat_entertainment': 'Entertainment',
      'cat_productivity': 'Productivity',
      'cat_music': 'Music',
      'cat_other': 'Other',
      'chart_total': 'Total',
      'detected_in_receipt': 'Receipt from {merchant}',
      'recent_emails_count': 'Recent Emails ({count})',
      'scan_complete_msg': 'Gmail subscription scan completed successfully!',
      'login_failed': 'Login failed',
      'scan_failed': 'Failed to trigger scan',
      'cancel_success': 'Subscription marked as canceled.',
      'cancel_failed': 'Failed to cancel subscription',
      'connected_gmail': 'Connected Gmail',
      'setting_weekly': 'Weekly',
      'setting_all_time': 'All time',
      'setting_currency': 'USD (\$)',
      'recent_emails': 'Recent Emails',
      'receipt_from': 'Receipt from',
    },
    'zh': {
      'welcome_title': '追踪、管理、取消\n您所有的订阅。',
      'welcome_subtitle': 'SubLens 通过扫描您的 Gmail 邮箱发现订阅，帮助您掌控财务。',
      'get_started': '开始使用',
      'connect_title': '连接您的 Gmail',
      'connect_desc': '我们将安全地访问您的电子邮件以检测订阅。我们绝不会阅读或共享您的邮件。',
      'connect_badge': '我们绝不会阅读或共享您的邮件',
      'continue_google': '使用 Google 账号登录',
      'disconnect_anytime': '您可以随时断开连接。',
      'scanning_title': '正在扫描您的 Gmail',
      'scanning_desc': '请稍候，我们正在分析您的邮件以检测订阅。',
      'in_progress': '正在进行中',
      'stop_scan': '停止扫描',
      'emails_scanned': '已扫描邮件数',
      'subs_found': '已发现订阅数',
      'time_elapsed': '已用时间',
      'hello': '你好，{name} 👋',
      'overview': '这是您的订阅总览',
      'active_subs': '活跃订阅',
      'monthly_spend': '月度总支出',
      'recent_subs': '最近订阅',
      'view_all': '查看全部',
      'start_new_scan': '开始新扫描',
      'your_subs': '您的订阅',
      'all': '全部',
      'active': '已激活',
      'canceled': '已取消',
      'billing_cycle': '计费周期',
      'next_charge': '下次扣费',
      'last_charge': '上次扣费',
      'detected_in': '检测来源',
      'confidence': '置信度评分',
      'recent_emails': '最近邮件',
      'cancel_guide': '取消指南',
      'mark_canceled': '标记为已取消',
      'how_to_cancel': '如何取消',
      'open_account': '打开服务账户',
      'step_1_title': '前往账户中心',
      'step_1_desc': '访问该服务网站并登录您的个人账户。',
      'step_2_title': '找到账单选项',
      'step_2_desc': '点击您的个人头像 > 账户 > 账单详情。',
      'step_3_title': '取消会员订阅',
      'step_3_desc': '点击“取消会员资格”，并根据界面提示完成确认。',
      'step_4_title': '确认取消',
      'step_4_desc': '取消成功后，您会收到一封官方发送的确认邮件。',
      'scan_history': '扫描历史',
      'insights': '洞察分析',
      'monthly_spend_trend': '月度消费走势',
      'top_categories': '热门分类',
      'total_saved': '本月节省',
      'this_month': '本月',
      'settings': '设置',
      'account': '账户管理',
      'preferences': '偏好设置',
      'scan_freq': '扫描频率',
      'sync_range': '邮件同步范围',
      'currency': '默认货币',
      'support': '支持服务',
      'help_center': '帮助中心',
      'contact_us': '联系我们',
      'privacy': '隐私政策',
      'terms': '服务条款',
      'log_out': '退出登录',
      'language': '语言 / Language',

      // Bottom Navigation
      'nav_home': '首页',
      'nav_subs': '我的订阅',
      'nav_scan': '扫描历史',
      'nav_insights': '消费分析',
      'nav_settings': '设置',

      // Cycles & Statuses
      'status_active': '已激活',
      'status_canceled': '已取消',
      'cycle_monthly': '按月扣费',
      'cycle_yearly': '按年扣费',
      'cycle_one_time': '单次买断',
      'cycle_unknown': '未知周期',
      'status_completed': '已完成',

      // Home stats subtext
      'home_active_subtext': '本月新增 2 项',
      'home_spend_subtext': '本月新增 \$12.30',

      // Dynamic units
      'unit_month': '/ 月',
      'unit_year': '/ 年',
      'unit_emails_scanned': '封邮件已扫描',
      'unit_subs_found': '个订阅已发现',
      'no_subs_found': '未发现订阅项目。',

      // Categories
      'cat_entertainment': '娱乐消遣',
      'cat_productivity': '效率工具',
      'cat_music': '音乐媒体',
      'cat_other': '其他类别',
      'chart_total': '总计',
      'detected_in_receipt': '来自 {merchant} 的收据',
      'recent_emails_count': '最近邮件 ({count})',
      'scan_complete_msg': 'Gmail 订阅扫描已成功完成！',
      'login_failed': '登录失败',
      'scan_failed': '扫描触发失败',
      'cancel_success': '订阅已标记为已取消。',
      'cancel_failed': '取消订阅失败',
      'connected_gmail': '已连接 Gmail',
      'setting_weekly': '每周',
      'setting_all_time': '所有时间',
      'setting_currency': 'USD (\$)',
      'recent_emails': '最近邮件',
      'receipt_from': '来自',
    }
  };

  String translate(String key) {
    return _localizedValues[locale]?[key] ?? key;
  }
}
